"""Added role table

Revision ID: 23a75585ce22
Revises: c29ba8023d71
Create Date: 2024-08-05 15:03:19.385152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23a75585ce22'
down_revision: Union[str, None] = 'c29ba8023d71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(length=20), nullable=True))
    op.alter_column('users', 'phone_num',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint('users_phone_num_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_phone_num_key', 'users', ['phone_num'])
    op.alter_column('users', 'phone_num',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('users', 'email')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
