"""Added role table

Revision ID: c5de53eb6208
Revises: 183f175bb74f
Create Date: 2024-08-05 16:42:47.260591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5de53eb6208'
down_revision: Union[str, None] = '183f175bb74f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buy_rice_delivery',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ricebox_id', sa.BigInteger(), nullable=False),
    sa.Column('rice_type_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rice_type_id'], ['rice_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ricebox_id'], ['ricebox.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buy_rice_delivery')
    # ### end Alembic commands ###
