services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - ./Backend/.env
    environment:
      - POSTGRES_PASSWORD=Son[1122002]
      - POSTGRES_DB=smart_ricebox_db
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: