version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5433:5432"
    env_file:
      - ./Backend/.env
    environment:
      - POSTGRES_PASSWORD=${database_password}
      - POSTGRES_DB=${database_name}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: